app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  compression:
    enabled: true
  port: 8080
spring:
  datasource:
    initialization-mode: always
    password: password
    url: jdbc:mysql://localhost:3306/schooling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
mybatis:
    mapper-locations: classpath*:META-INF/mybatis/mapper/*.xml
#    configuration:
#        map-underscore-to-camkel-case: true
#        default-fetch-size: 100
#        default-statement-timeout: 30